use DersOrnek
go
SET IDENTITY_INSERT yok_universiteler ON
INSERT INTO yok_universiteler (ID, Isim) VALUES
(101, 'Abant Ýzzet Baysal Üniversitesi'),
(235, 'Acýbadem Üniversitesi'),
(167, 'Adýyaman Üniversitesi'),
(102, 'Adnan Menderes Üniversitesi'),
(103, 'Afyon Kocatepe Üniversitesi'),
(171, 'Aðrý Ýbrahim Çeçen Üniversitesi'),
(155, 'Ahi Evran Üniversitesi'),
(425, 'Akaki Tsereteli Devlet Üniversitesi'),
(104, 'Akdeniz Üniversitesi'),
(163, 'Aksaray Üniversitesi'),
(169, 'Amasya Üniversitesi'),
(105, 'Anadolu Üniversitesi'),
(106, 'Ankara Üniversitesi'),
(187, 'Ardahan Üniversitesi'),
(178, 'Artvin Çoruh Üniversitesi'),
(107, 'Atatürk Üniversitesi'),
(201, 'Atýlým Üniversitesi'),
(262, 'Avrasya Üniversitesi'),
(402, 'Azerbaycan Devlet Diller Üniversitesi '),
(406, 'Azerbaycan Devlet Ýktisat Üniversitesi'),
(405, 'Azerbaycan Devlet Kültür Ve Güzel Sanatlar Üniversitesi'),
(403, 'Azerbaycan Devlet Neft Akademisi '),
(410, 'Azerbaycan Devlet Pedagoji Üniversitesi'),
(488, 'Azerbaycan Mimarlýk Ve Ýnþaat Üniversitesi'),
(404, 'Azerbaycan Teknik Üniversitesi'),
(409, 'Azerbaycan Týp Üniversitesi'),
(202, 'Bahçeþehir Üniversitesi'),
(407, 'Bakü Devlet Üniversitesi'),
(408, 'Bakü Slavyan Üniversitesi'),
(108, 'Balýkesir Üniversitesi'),
(188, 'Bartýn Üniversitesi'),
(203, 'Baþkent Üniversitesi'),
(186, 'Batman Üniversitesi'),
(422, 'Batum Þota Rustaveli Devlet Üniversitesi'),
(189, 'Bayburt Üniversitesi'),
(204, 'Beykent Üniversitesi'),
(255, 'Bezm-i Âlem Vakýf Üniversitesi'),
(179, 'Bilecik Üniversitesi'),
(205, 'Bilkent Üniversitesi'),
(183, 'Bingöl Üniversitesi'),
(180, 'Bitlis Eren Üniversitesi'),
(109, 'Boðaziçi Üniversitesi'),
(166, 'Bozok Üniversitesi'),
(196, 'Bursa Teknik Üniversitesi'),
(110, 'Celal Bayar Üniversitesi'),
(111, 'Cumhuriyet Üniversitesi'),
(206, 'Çað Üniversitesi'),
(112, 'Çanakkale Onsekiz Mart Üniversitesi'),
(207, 'Çankaya Üniversitesi'),
(177, 'Çankýrý Karatekin Üniversitesi'),
(113, 'Çukurova Üniversitesi'),
(114, 'Dicle Üniversitesi'),
(301, 'Doðu Akdeniz Üniversitesi'),
(208, 'Doðuþ Üniversitesi'),
(115, 'Dokuz Eylül Üniversitesi'),
(116, 'Dumlupýnar Üniversitesi'),
(157, 'Düzce Üniversitesi'),
(117, 'Ege Üniversitesi'),
(118, 'Erciyes Üniversitesi'),
(162, 'Erzincan Üniversitesi'),
(143, 'Eskiþehir Osmangazi Üniversitesi'),
(256, 'Fatih Sultan Mehmet Vakýf Üniversitesi'),
(209, 'Fatih Üniversitesi'),
(119, 'Fýrat Üniversitesi'),
(120, 'Galatasaray Üniversitesi'),
(121, 'Gazi Üniversitesi'),
(122, 'Gaziantep Üniversitesi'),
(245, 'Gazikent Üniversitesi'),
(123, 'Gaziosmanpaþa Üniversitesi'),
(154, 'Gebze Yüksek Teknoloji Enstitüsü'),
(251, 'Gedik Üniversitesi'),
(236, 'Gediz Üniversitesi'),
(484, 'Gence Devlet Üniversitesi'),
(164, 'Giresun Üniversitesi'),
(302, 'Girne Amerikan Üniversitesi'),
(153, 'Gülhane Askeri Týp Akademisi'),
(190, 'Gümüþhane Üniversitesi'),
(124, 'Hacettepe Üniversitesi'),
(191, 'Hakkari Üniversitesi'),
(210, 'Haliç Üniversitesi'),
(125, 'Harran Üniversitesi'),
(165, 'Hitit Üniversitesi'),
(430, 'Hoca Ahmet Yesevi Uluslararasý Türk-kazak Üniversitesi'),
(192, 'Iðdýr Üniversitesi'),
(211, 'Iþýk Üniversitesi'),
(444, 'Ýktisat Ve Giriþimcilik Üniversitesi'),
(126, 'Ýnönü Üniversitesi'),
(249, 'Ýstanbul 29 Mayýs Üniversitesi'),
(230, 'Ýstanbul Arel Üniversitesi'),
(225, 'Ýstanbul Aydýn Üniversitesi'),
(212, 'Ýstanbul Bilgi Üniversitesi'),
(228, 'Ýstanbul Bilim Üniversitesi'),
(234, 'Ýstanbul Geliþim Üniversitesi'),
(258, 'Ýstanbul Kemerburgaz Üniversitesi'),
(213, 'Ýstanbul Kültür Üniversitesi'),
(247, 'Ýstanbul Medipol Üniversitesi'),
(264, 'Ýstanbul Sabahattin Zaim Üniversitesi'),
(244, 'Ýstanbul Þehir Üniversitesi'),
(128, 'Ýstanbul Teknik Üniversitesi'),
(220, 'Ýstanbul Ticaret Üniversitesi'),
(127, 'Ýstanbul Üniversitesi'),
(219, 'Ýzmir Ekonomi Üniversitesi'),
(199, 'Ýzmir Katip Çelebi Üniversitesi'),
(231, 'Ýzmir Üniversitesi'),
(129, 'Ýzmir Yüksek Teknoloji Enstitüsü'),
(214, 'Kadir Has Üniversitesi'),
(130, 'Kafkas Üniversitesi'),
(131, 'Kahramanmaraþ Sütçü Ýmam Üniversitesi'),
(175, 'Karabük Üniversitesi'),
(132, 'Karadeniz Teknik Üniversitesi'),
(170, 'Karamanoðlu Mehmetbey Üniversitesi'),
(156, 'Kastamonu Üniversitesi'),
(443, 'Kýrgýzistan-türkiye Manas Üniversitesi'),
(133, 'Kýrýkkale Üniversitesi'),
(181, 'Kýrklareli Üniversitesi'),
(176, 'Kilis 7 Aralýk Üniversitesi'),
(134, 'Kocaeli Üniversitesi'),
(215, 'Koç Üniversitesi'),
(475, 'Korkut Ata Kýzýlorda Devlet Üniversitesi'),
(241, 'Kto Karatay Üniversitesi'),
(303, 'Lefke Avrupa Üniversitesi'),
(216, 'Maltepe Üniversitesi'),
(185, 'Mardin Artuklu Üniversitesi'),
(135, 'Marmara Üniversitesi'),
(158, 'Mehmet Akif Ersoy Üniversitesi'),
(237, 'Melikþah Üniversitesi'),
(136, 'Mersin Üniversitesi'),
(243, 'Mevlana Üniversitesi'),
(137, 'Mimar Sinan Güzel Sanatlar Üniversitesi'),
(138, 'Muðla Üniversitesi'),
(139, 'Mustafa Kemal Üniversitesi'),
(184, 'Muþ Alparslan Üniversitesi'),
(161, 'Namýk Kemal Üniversitesi'),
(174, 'Nevþehir Üniversitesi'),
(140, 'Niðde Üniversitesi'),
(261, 'Nuh Naci Yazgan Üniversitesi'),
(223, 'Okan Üniversitesi');
INSERT INTO yok_universiteler (ID, Isim) VALUES
(141, 'Ondokuz Mayýs Üniversitesi'),
(168, 'Ordu Üniversitesi'),
(142, 'Orta Doðu Teknik Üniversitesi'),
(182, 'Osmaniye Korkut Ata Üniversitesi'),
(232, 'Özyeðin Üniversitesi'),
(144, 'Pamukkale Üniversitesi'),
(238, 'Piri Reis Üniversitesi'),
(160, 'Rize Üniversitesi'),
(217, 'Sabancý Üniversitesi'),
(145, 'Sakarya Üniversitesi'),
(146, 'Selçuk Üniversitesi'),
(173, 'Siirt Üniversitesi'),
(172, 'Sinop Üniversitesi'),
(489, 'Sumgayýt Devlet Üniversitesi'),
(147, 'Süleyman Demirel Üniversitesi'),
(257, 'Süleyman Þah Üniversitesi'),
(193, 'Þýrnak Üniversitesi'),
(259, 'Þifa Üniversitesi'),
(226, 'Tobb Ekonomi Ve Teknoloji Üniversitesi'),
(253, 'Toros Üniversitesi'),
(148, 'Trakya Üniversitesi'),
(194, 'Tunceli Üniversitesi'),
(246, 'Turgut Özal Üniversitesi'),
(260, 'Türk Hava Kurumu Üniversitesi'),
(221, 'Ufuk Üniversitesi'),
(483, 'Ukrayna Ulusal Teknik Üniversitesi'),
(149, 'Uludað Üniversitesi'),
(496, 'Uluslararasý Saraybosna Üniversitesi'),
(304, 'Uluslararasi Kýbrýs Üniversitesi'),
(159, 'Uþak Üniversitesi'),
(305, 'Yakýn Doðu Üniversitesi'),
(195, 'Yalova Üniversitesi'),
(222, 'Yaþar Üniversitesi'),
(218, 'Yeditepe Üniversitesi'),
(242, 'Yeni Yüzyýl Üniversitesi'),
(503, 'Yýldýrým Beyazýt Üniversitesi'),
(150, 'Yýldýz Teknik Üniversitesi'),
(151, 'Yüzüncü Yýl Üniversitesi'),
(239, 'Zirve Üniversitesi'),
(152, 'Zonguldak Karaelmas Üniversitesi')
SET IDENTITY_INSERT yok_Universiteler OFF
select count(*) from yok_Universiteler
